services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=mysecret123
      - DATABASE_URL=postgresql://vertragsuser:geheim@db:5432/vertragsdb?schema=public
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vertragsuser
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: vertragsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
